
apiVersion: 1

datasources:
  - name: TimescaleDB PFA
    uid: timescaledb-pfa
    type: grafana-postgresql-datasource
    access: proxy
    url: timescaledb:5432
    user: pfa
    database: photovoltaique
    isDefault: true
    editable: true
    secureJsonData:
      password: pfa2026
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
